"""followers

Revision ID: 53daa63fb4c8
Revises: 44f2935e6018
Create Date: 2020-07-16 20:21:18.619572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53daa63fb4c8'
down_revision = '44f2935e6018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
