"""private messages refactoring

Revision ID: b97774daa389
Revises: b8b6d63c3ba4
Create Date: 2020-07-31 08:56:47.560443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97774daa389'
down_revision = 'b8b6d63c3ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('recipient_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['recipient_id'], ['id'])
    op.drop_column('message', 'recepient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('recepient_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'user', ['recepient_id'], ['id'])
    op.drop_column('message', 'recipient_id')
    # ### end Alembic commands ###
